# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets
import sys
from PyQt5 import QtWidgets, QtCore, QtGui 
from PyQt5.QtCore import *
from PyQt5.QtGui import *
from PyQt5.QtWidgets import *
import cv2

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):

        self.imgName =[]
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1247, 541)
        #禁止窗口最大化
        MainWindow.setWindowFlags(QtCore.Qt.WindowMinimizeButtonHint|QtCore.Qt.WindowCloseButtonHint|QtCore.Qt.MSWindowsFixedSizeDialogHint)
        #setWindowFlags(Qt.WindowMinimizeButtonHint)
        #setWindowFlags(Qt.WindowCloseButtonHint)  
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget") 
        #初始化lab1图片
        self.lab1 = QtWidgets.QLabel(self.centralWidget)
        self.lab1.setGeometry(QtCore.QRect(10, 50, 480, 480))
        self.lab1.setText("")
        self.lab1.setObjectName("lab1")
        self.lab1.setPixmap(QPixmap("./photo1.png"))
        op = QtWidgets.QGraphicsOpacityEffect()
        # 设置透明度的值，0.0到1.0，最小值0是透明，1是不透明
        op.setOpacity(0.6)
        self.lab1.setGraphicsEffect(op)

        font = QtGui.QFont()
        font.setFamily("蝉羽真颜金戈") #括号里可以设置成自己想要的其它字体
        font.setPointSize(20)   #括号里的数字可以设置成自己想要的字体大小

        #文本框
        self.textEdit = QtWidgets.QTextEdit(self.centralWidget)
        self.textEdit.setGeometry(QtCore.QRect(10, 50, 480, 480))
        self.textEdit.setPlaceholderText("请输入正文")
        self.textEdit.setStyleSheet("QTextEdit{color: black; background-color: transparent; border:1px solid black;}")
        self.textEdit.setObjectName("textEdit")
        self.textEdit.setFont(font)
        
        #布局
        self.groupBox = QtWidgets.QGroupBox(self.centralWidget)
        self.groupBox.setGeometry(QtCore.QRect(500, 20, 741, 511))
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setContentsMargins(11, 11, 11, 11)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.btnAdd = QtWidgets.QPushButton(self.groupBox)

        #按钮控件以及图标
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("./icons/images/316.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnAdd.setIcon(icon)
        self.btnAdd.setObjectName("btnAdd")
        self.gridLayout.addWidget(self.btnAdd, 0, 0, 1, 2)
        self.btnRemove = QtWidgets.QPushButton(self.groupBox)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("./icons/images/318.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnRemove.setIcon(icon1)
        self.btnRemove.setObjectName("btnRemove")
        self.gridLayout.addWidget(self.btnRemove, 0, 2, 1, 3)
        self.btnClear = QtWidgets.QPushButton(self.groupBox)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("./icons/images/214.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnClear.setIcon(icon2)
        self.btnClear.setObjectName("btnClear")
        self.gridLayout.addWidget(self.btnClear, 0, 5, 1, 3)
        self.selectbtn = QtWidgets.QPushButton(self.groupBox)
        self.selectbtn.setObjectName("selectbtn")
        self.gridLayout.addWidget(self.selectbtn, 0, 8, 1, 2)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 2)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")

        #音乐播放列表
        self.gridLayout.addWidget(self.label_3, 1, 5, 1, 2)
        self.listWidget = QtWidgets.QListWidget(self.groupBox)
        self.listWidget.setObjectName("listWidget")
        self.gridLayout.addWidget(self.listWidget, 2, 0, 1, 5)

        #图片播放列表
        self.listView = QtWidgets.QListView(self.groupBox)
        self.listView.setObjectName("listView")
        self.gridLayout.addWidget(self.listView, 2, 5, 1, 5)
        
        self.btnPlay = QtWidgets.QPushButton(self.groupBox)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("./icons/images/620.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnPlay.setIcon(icon3)
        self.btnPlay.setObjectName("btnPlay")
        self.gridLayout.addWidget(self.btnPlay, 3, 0, 1, 1)
        self.btnPause = QtWidgets.QPushButton(self.groupBox)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("./icons/images/622.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnPause.setIcon(icon4)
        self.btnPause.setObjectName("btnPause")
        self.gridLayout.addWidget(self.btnPause, 3, 1, 1, 2)
        self.btnStop = QtWidgets.QPushButton(self.groupBox)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("./icons/images/624.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnStop.setIcon(icon5)
        self.btnStop.setObjectName("btnStop")
        self.gridLayout.addWidget(self.btnStop, 3, 3, 1, 1)
        self.btnPrevious = QtWidgets.QPushButton(self.groupBox)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("./icons/images/616.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnPrevious.setIcon(icon6)
        self.btnPrevious.setObjectName("btnPrevious")
        self.gridLayout.addWidget(self.btnPrevious, 3, 4, 1, 2)
        self.btnNext = QtWidgets.QPushButton(self.groupBox)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("./icons/images/630.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnNext.setIcon(icon7)
        self.btnNext.setObjectName("btnNext")
        self.gridLayout.addWidget(self.btnNext, 3, 6, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(23, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 3, 7, 1, 1)
        self.sliderVolumn = QtWidgets.QSlider(self.groupBox)
        self.sliderVolumn.setMaximum(100)
        self.sliderVolumn.setProperty("value", 100)
        self.sliderVolumn.setOrientation(QtCore.Qt.Horizontal)
        self.sliderVolumn.setObjectName("sliderVolumn")
        self.gridLayout.addWidget(self.sliderVolumn, 3, 9, 1, 1)
        self.line = QtWidgets.QFrame(self.groupBox)
        self.line.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 4, 0, 1, 10)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(9)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")

        #曲目
        self.LabCurMedia = QtWidgets.QLabel(self.groupBox)
        self.LabCurMedia.setMinimumSize(QtCore.QSize(100, 0))
        self.LabCurMedia.setObjectName("LabCurMedia")
        self.horizontalLayout_2.addWidget(self.LabCurMedia)

        #音乐进度条
        self.sliderPosition = QtWidgets.QSlider(self.groupBox)
        self.sliderPosition.setTracking(False)
        self.sliderPosition.setOrientation(QtCore.Qt.Horizontal)
        self.sliderPosition.setObjectName("sliderPosition")
        self.horizontalLayout_2.addWidget(self.sliderPosition)

        #音量进度条
        self.LabRatio = QtWidgets.QLabel(self.groupBox)
        self.LabRatio.setMinimumSize(QtCore.QSize(80, 0))
        self.LabRatio.setObjectName("LabRatio")
        self.horizontalLayout_2.addWidget(self.LabRatio)
        self.gridLayout.addLayout(self.horizontalLayout_2, 5, 0, 1, 10)

        self.btnSound = QtWidgets.QPushButton(self.groupBox)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("./icons/images/volumn.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnSound.setIcon(icon8)
        self.btnSound.setFlat(True)
        self.btnSound.setObjectName("btnSound")
        self.gridLayout.addWidget(self.btnSound, 3, 8, 1, 1)

        #标题框
        self.lineEdit = QtWidgets.QLineEdit(self.centralWidget)
        self.lineEdit.setGeometry(QtCore.QRect(10, 10, 480, 35))
        self.lineEdit.setPlaceholderText("请输入标题")
        self.lineEdit.setAlignment(Qt.AlignHCenter)
        self.lineEdit.setStyleSheet("QLineEdit{color: black; background-color: transparent; border:1px solid black;}")
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit.setFont(font)
        MainWindow.setCentralWidget(self.centralWidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Demo10_1，音乐播放器"))
        self.groupBox.setTitle(_translate("MainWindow", "播放列表"))
        self.btnAdd.setText(_translate("MainWindow", "添加"))
        self.btnRemove.setText(_translate("MainWindow", "移除"))
        self.btnClear.setText(_translate("MainWindow", "清空"))
        self.selectbtn.setText(_translate("MainWindow", "选择图片"))
        self.label_2.setText(_translate("MainWindow", "音乐播放列表"))
        self.label_3.setText(_translate("MainWindow", "背景图片列表"))
        self.btnPlay.setToolTip(_translate("MainWindow", "播放"))
        self.btnPlay.setText(_translate("MainWindow", "播放"))
        self.btnPause.setToolTip(_translate("MainWindow", "暂停"))
        self.btnPause.setText(_translate("MainWindow", "暂停"))
        self.btnStop.setToolTip(_translate("MainWindow", "停止"))
        self.btnStop.setText(_translate("MainWindow", "停止"))
        self.btnPrevious.setToolTip(_translate("MainWindow", "前一曲目"))
        self.btnPrevious.setText(_translate("MainWindow", "上一首"))
        self.btnNext.setToolTip(_translate("MainWindow", "下一曲目"))
        self.btnNext.setText(_translate("MainWindow", "下一首"))
        self.LabCurMedia.setText(_translate("MainWindow", "无曲目"))
        self.LabRatio.setText(_translate("MainWindow", "进度"))
        self.btnSound.setText(_translate("MainWindow", "音量"))
